package test;


import test.*;
import drawer.DrawerItem;
import java.awt.Color;
import drawer.Drawer;
import drawer.DrawerController;
import drawer.EventDrawer;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import javax.swing.UIManager;
import com.formdev.*;
import com.formdev.flatlaf.*;


public class Test extends JFrame {
	private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private DrawerController drawer;

    public Test() {
        initComponents();
        drawer = Drawer.newDrawer(this)
                .background(new Color(90, 90, 90))
                .closeOnPress(true)
                .backgroundTransparent(0.3f)
                .leftDrawer(true)
                .enableScroll(true)
                .enableScrollUI(false)
                .headerHeight(160)
                .header(new Header())
                .space(3)
                
                .addChild(new DrawerItem("Nhân viên").icon(new ImageIcon(getClass().getResource("/icons/user.png"))).build())
                .addChild(new DrawerItem("Contacts").icon(new ImageIcon(getClass().getResource("/icons/cont.png"))).build())
                .addChild(new DrawerItem("Report").icon(new ImageIcon(getClass().getResource("/icons/report.png"))).build())
                .addChild(new DrawerItem("Income").icon(new ImageIcon(getClass().getResource("/icons/income.png"))).build())
                .addChild(new DrawerItem("Expense").icon(new ImageIcon(getClass().getResource("/icons/expense.png"))).build())
                .addChild(new DrawerItem("Datas").icon(new ImageIcon(getClass().getResource("/icons/data.png"))).build())
                .addFooter(new DrawerItem("Tài khoản").icon(new ImageIcon(getClass().getResource("/icons/user.png"))).build())
//                .addFooter(new DrawerItem("Exit").icon(new ImageIcon(getClass().getResource("/icons/exit.png"))).build())
                .event(new EventDrawer() {
                    @Override
                    public void selected(int index, DrawerItem item) {
                     if(drawer.isShow()){
                         drawer.hide();
                     }
                    }
                })
                .build();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jButton1 = new JButton();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();

        setDefaultCloseOperation(EXIT_ON_CLOSE);

        jButton1.setText("|||");
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }

    private void jButton1ActionPerformed(ActionEvent evt) {
        if (drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }

    
    public static void main(String args[]) {
        FlatLightLaf.setup();
    	new Test().setVisible(true);
    }
}
