package gui;


import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;

import org.kordamp.ikonli.swing.FontIcon;

import com.formdev.flatlaf.FlatLightLaf;

import drawer.Drawer;
import drawer.DrawerController;
import drawer.DrawerItem;
import drawer.EventDrawer;


public class GUI_TrangChu extends JFrame implements ActionListener {
	private static final long serialVersionUID = 1L;
	private JButton jButton1;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private DrawerController drawer;

    
    public GUI_TrangChu() {
        initComponents();
        
                
        drawer = Drawer.newDrawer(this)
                .background(new Color(90, 90, 90))
                .closeOnPress(true)
                .backgroundTransparent(0.3f)
                .leftDrawer(true)
                .enableScroll(true)
                .enableScrollUI(false)
                .headerHeight(160)
                .header(new Header())
                .space(3)
                .addChild(new DrawerItem("Trang chủ").icon(new ImageIcon(getClass().getResource("/icons/home.png"))).build())
                .addChild(new DrawerItem("Danh mục").icon(new ImageIcon(getClass().getResource("/icons/category.png"))).build())
                .addChild(new DrawerItem("Nhân viên").icon(new ImageIcon(getClass().getResource("/icons/category.png"))).build())
                .addChild(new DrawerItem("Tính lương").icon(new ImageIcon(getClass().getResource("/icons/salary.png"))).build())
                .addChild(new DrawerItem("Hệ thống").icon(new ImageIcon(getClass().getResource("/icons/file-type-light-config.png"))).build())
                .addChild(new DrawerItem("Trợ giúp").icon(new ImageIcon(getClass().getResource("/icons/help-outline.png"))).build())
                .addFooter(new DrawerItem("Tài khoản").icon(new ImageIcon(getClass().getResource("/icons/user.png"))).build())
//                .addFooter(new DrawerItem("Exit").icon(new ImageIcon(getClass().getResource("/icons/exit.png"))).build())
                .event(new EventDrawer() {
                    @Override
                    public void selected(int index, DrawerItem item) {
                     if(drawer.isShow()){
                         drawer.hide();
                     }
                    }
                })
                .build();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jButton1 = new JButton();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();

        setDefaultCloseOperation(EXIT_ON_CLOSE);

        jButton1.setText("|||");
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }
    

    private void jButton1ActionPerformed(ActionEvent evt) {
        if (drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }
	

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		
	}
	
	
	public static void main(String[] args) {
		FlatLightLaf.setup();
		
		new GUI_TrangChu().setVisible(true);
	}
}
